plugins { id 'com.android.application' }

android {
    namespace 'com.baskahocaa.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.baskahocaa.app'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }

    signingConfigs {
        baskahocaa {
            storeFile file('baskahocaa-key.jks')
            storePassword 'baskahocaa123'
            keyAlias 'baskahocaa'
            keyPassword 'baskahocaa123'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.baskahocaa
        }
        release {
            signingConfig signingConfigs.baskahocaa
            minifyEnabled false
        }
    }
}
